# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93f2b3ff3ffa9c965d67d6baed989882710c24b7610462d8d55e89fdbab886b5312e0015150b2fd7cb35ce23ee1298dc6f892aeff6b80572614631ce72ec8c6d

test:
  secret_key_base: 383ad5dc6cbf937f2e47e242887dbec61e40fae90b60ec3901774b7620c41465496d3b07a17e02791cb217872393c6578fd1c3f9d1343188b403afd7207f6c30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
